# This configuration file should contain all required configuration parameters
# for the ingest workflow to run to completion.

# Required to fetch from NCBI Datasets
ncbi_taxon_id: "3052225"

# The list of NCBI Datasets fields to include from NCBI Datasets output
# These need to be the "mnemonics" of the NCBI Datasets fields, see docs for full list of fields
# https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/command-line/dataformat/tsv/dataformat_tsv_virus-genome/#fields
# Note: the "accession" field MUST be provided to match with the sequences
ncbi_datasets_fields:
  - accession
  - sourcedb
  - sra-accs
  - isolate-lineage
  - geo-region
  - geo-location
  - isolate-collection-date
  - release-date
  - update-date
  - length
  - host-name
  - is-lab-host
  - isolate-lineage-source
  - biosample-acc
  - submitter-names
  - submitter-affiliation
  - submitter-country

# Config parameters related to the curate pipeline
curate:
  geolocation_rules_url: "https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv"
  local_geolocation_rules: "defaults/geolocation_rules.tsv"
  field_map:
    accession: accession
    accession_version: accession_version
    sourcedb: database
    sra-accs: sra_accessions
    isolate-lineage: strain
    geo-region: region
    geo-location: location
    isolate-collection-date: date
    release-date: date_released
    update-date: date_updated
    length: length
    host-name: host
    is-lab-host: is_lab_host
    isolate-lineage-source: sample_type
    biosample-acc: biosample_accessions
    submitter-names: authors
    submitter-affiliation: institution
    submitter-country: submitter_country
  date_fields: ['date', 'date_released', 'date_updated']
  expected_date_formats: ['%Y', '%Y-%m', '%Y-%m-%d', '%Y-%m-%dT%H:%M:%SZ']
  # The expected field that contains the GenBank geo_loc_name
  genbank_location_field: location
  titlecase:
    abbreviations: ['USA']
    articles: ['and', 'd', 'de', 'del', 'des', 'di', 'do', 'en', 'l', 'la', 'las', 'le', 'los', 'nad', 'of', 'op', 'sur', 'the', 'y']
    fields: ['region', 'country', 'division', 'location']
  authors_field: 'authors'
  authors_default_value: '?'
  abbr_authors_field: 'abbr_authors'
  annotations: "defaults/annotations.tsv"
  annotations_id: 'accession'
  output_id_field: "accession"
  output_sequence_field: "sequence"
  # The field in the NDJSON record that contains the actual GenBank accession
  genbank_accession: 'accession'
  metadata_columns:
    - accession
    - strain
    - date
    - date_released
    - date_updated
    - region
    - country
    - division
    - location
    - length
    - host
    - is_lab_host
    - sra_accessions
    - abbr_authors
    - institution
    - submitter_country
    - sample_type
    - url
