"""
This is the main ingest Snakefile that orchestrates the full ingest workflow
and defines its default outputs.
"""
# The workflow filepaths are written relative to this Snakefile's base directory
workdir: workflow.current_basedir

# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "defaults/config.yaml"


include: "rules/fetch_from_ncbi.smk"
include: "rules/curate.smk"


rule all:
    input:
        "results/sequences.fasta",
        "results/metadata.tsv",
