# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

# Define wildcards used for building trees in the workflow, also used in the intermediate files or auxillariary default file names.
# {build} represents focus of samples to be analyzed
builds: ["human", "I", "II", "all"]
# {gene} represents the nipah genes for Nextclade and augur ancestral calls
genes: ["N", "M", "F", "G", "L", "P"]

# Sequences must be FASTA and metadata must be TSV
# Both files must be zstd compressed

inputs:
  - name: ncbi
    sequences: "https://data.nextstrain.org/files/workflows/nipah/sequences.fasta.zst"
    metadata: "https://data.nextstrain.org/files/workflows/nipah/metadata.tsv.zst"

strain_id_field: "accession"

filter:
  exclude: "exclude.txt"
  min_length: 17000
  exclude_where:
    human: "--exclude-where host!='Homo sapiens'"
    I: "--exclude-where country=Malaysia country=USA country=Cambodia country=''"
    II: "--exclude-where country=India country=Bangladesh country=Thailand"
    all: ""

nextclade:
  reference_fasta: "reference.fasta"
  genemap: "genemap.gff"

mask:
  mask_from_beginning: 100
  mask_from_end: 100
  mask_flags: "--mask-terminal-gaps"

tree:
  args: "'-ninit 10 -n 4 -czb -T AUTO'"

refine:
  # Estimate clock_rate from auspice/nipah_human.json and auspice/nipah_I.json rate
  refine_flags: " --timetree --precision 3 --keep-polytomies --date-inference marginal --date-confidence --clock-filter-iqd 0 --clock-rate 0.000155 --coalescent opt"

ancestral:
  reference_gb: "reference.gb"

clades:
  clades_defining_mutations: "clades.tsv"

export:
  auspice_config: "auspice_config.json"
  description: "description.md"